### ISSUE TITLE
broken link for intro to codebooks

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/factcuratoR#1]
This link is broken: 

https://idahoagstats.github.io/factcuratoR/docs/articles/intro_codebooks.html

**Comment by jpiaskowski** [comment]
it's being linked from this page:

ttps://idahoagstats.github.io/factcuratoR/

At the bottom, "See..."

**Comment by justjacqueline** [comment]
Thanks for catching that, @jpiaskowski!
