### ISSUE TITLE
Dependency issue when using pkgdown::build_article()

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/factcuratoR#2]
Tried running this:

`pkgdown::build_article("example_cultivar_matching")`

and get this error:

```
Quitting from lines 23-29 (example_cultivar_matching.Rmd) 
Error : package or namespace load failed for 'factcuratoR':
 .onLoad failed in loadNamespace() for 'dm', details:
  call: NULL
  error: DiagrammeR and DiagrammeRsvg packages needed for this function to work. Please install it.
```

Should these be included in the DESCRIPTION file? Since I'm running pckdown function and not a standard package function, maybe not. After installing those packages, the function ran fine.

**Comment by justjacqueline** [comment]
Hi @jpiaskowski, 

library(factcuratoR) is run on line 25, and I think it is the DESCRIPTION file that is causing this (correct) error letting the user know that the dm package must be installed.

This information is in the Imports section in the DESCRIPTION file.
