### ISSUE TITLE
intro_validation.Rmd questions

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/factcuratoR#3]
I am not clear on this statement and why it is needed:

"It may be easiest to point the most cleaned up version of the data to a new 
variable (e.g. df_validate below) so that the calls to the validation functions
don't need to be updated every time there is a more cleaned up version of the data."
###

In this statement, should be consider reversing the output?

"**Note:** To make human review easier, the output is automatically ordered so 
that the columns present the data are at the top and that the 
REQUIRED but missing columns are at the bottom."

**Comment by justjacqueline** [comment]
Part 1: Let's discuss this in our meeting!  It may be unnecessary information. 

Part 2: Changed the output and removed that note in the vignette! https://github.com/IdahoAgStats/factcuratoR/commit/059e5eef724f61eb3eb892804de28be8a175ee5e
