### ISSUE TITLE
Handle duplicate traits in create_rules()

### ISSUE THREAD

**Issue by justjacqueline** [IdahoAgStats/factcuratoR#6]
Right now, the validation function `create_rules()` pulls traits.csv, which contains the traits for all crops.

As more crops are added, there may be non-unique names (for example rows for yield_bu_acre for both wheat and barley). 

create_rules() can take the argument `crop_types`, which is to select the traits that are related to the desired crops.
If both of these crops are selected using crop_types = c("wheat", "barley") or crop_types = NULL (which keeps all of the traits in the traits.csv file) the validation functions (create_rules() and confront_data() will fail.  The functions should be okay for if a single crop is selected.

**Comment by emilymg** [comment]
Validation functions can now take multiple crop_types, and filter the output for only crops selected in the crop_types argument.
